
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.purumod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.purumod.block.SpruceWoodenStoolBlock;
import net.mcreator.purumod.block.SpruceTinyLog12Block;
import net.mcreator.purumod.block.SpruceTinyLog11Block;
import net.mcreator.purumod.block.SpruceTinyLog10Block;
import net.mcreator.purumod.block.SpruceTinyLog09Block;
import net.mcreator.purumod.block.SpruceTinyLog08Block;
import net.mcreator.purumod.block.SpruceTinyLog07Block;
import net.mcreator.purumod.block.SpruceTinyLog06Block;
import net.mcreator.purumod.block.SpruceTinyLog05Block;
import net.mcreator.purumod.block.SpruceTinyLog04Block;
import net.mcreator.purumod.block.SpruceTinyLog03Block;
import net.mcreator.purumod.block.SpruceTinyLog02Block;
import net.mcreator.purumod.block.SpruceTinyLog01Block;
import net.mcreator.purumod.block.OakWoodenStoolBlock;
import net.mcreator.purumod.block.OakWoodenChairBlock;
import net.mcreator.purumod.block.OakTinyLog12Block;
import net.mcreator.purumod.block.OakTinyLog11Block;
import net.mcreator.purumod.block.OakTinyLog10Block;
import net.mcreator.purumod.block.OakTinyLog09Block;
import net.mcreator.purumod.block.OakTinyLog08Block;
import net.mcreator.purumod.block.OakTinyLog07Block;
import net.mcreator.purumod.block.OakTinyLog06Block;
import net.mcreator.purumod.block.OakTinyLog05Block;
import net.mcreator.purumod.block.OakTinyLog04Block;
import net.mcreator.purumod.block.OakTinyLog03Block;
import net.mcreator.purumod.block.OakTinyLog02Block;
import net.mcreator.purumod.block.OakTinyLog01Block;
import net.mcreator.purumod.block.JungleWoodenStoolBlock;
import net.mcreator.purumod.block.JungleTinyLog12Block;
import net.mcreator.purumod.block.JungleTinyLog11Block;
import net.mcreator.purumod.block.JungleTinyLog10Block;
import net.mcreator.purumod.block.JungleTinyLog09Block;
import net.mcreator.purumod.block.JungleTinyLog08Block;
import net.mcreator.purumod.block.JungleTinyLog07Block;
import net.mcreator.purumod.block.JungleTinyLog06Block;
import net.mcreator.purumod.block.JungleTinyLog05Block;
import net.mcreator.purumod.block.JungleTinyLog04Block;
import net.mcreator.purumod.block.JungleTinyLog03Block;
import net.mcreator.purumod.block.JungleTinyLog02Block;
import net.mcreator.purumod.block.JungleTinyLog01Block;
import net.mcreator.purumod.block.DarkOakWoodenStoolBlock;
import net.mcreator.purumod.block.DarkOakTinyLog12Block;
import net.mcreator.purumod.block.DarkOakTinyLog11Block;
import net.mcreator.purumod.block.DarkOakTinyLog10Block;
import net.mcreator.purumod.block.DarkOakTinyLog09Block;
import net.mcreator.purumod.block.DarkOakTinyLog08Block;
import net.mcreator.purumod.block.DarkOakTinyLog07Block;
import net.mcreator.purumod.block.DarkOakTinyLog06Block;
import net.mcreator.purumod.block.DarkOakTinyLog05Block;
import net.mcreator.purumod.block.DarkOakTinyLog04Block;
import net.mcreator.purumod.block.DarkOakTinyLog03Block;
import net.mcreator.purumod.block.DarkOakTinyLog02Block;
import net.mcreator.purumod.block.DarkOakTinyLog01Block;
import net.mcreator.purumod.block.BirchWoodenStoolBlock;
import net.mcreator.purumod.block.BirchTinyLog12Block;
import net.mcreator.purumod.block.BirchTinyLog11Block;
import net.mcreator.purumod.block.BirchTinyLog10Block;
import net.mcreator.purumod.block.BirchTinyLog09Block;
import net.mcreator.purumod.block.BirchTinyLog08Block;
import net.mcreator.purumod.block.BirchTinyLog07Block;
import net.mcreator.purumod.block.BirchTinyLog06Block;
import net.mcreator.purumod.block.BirchTinyLog05Block;
import net.mcreator.purumod.block.BirchTinyLog04Block;
import net.mcreator.purumod.block.BirchTinyLog03Block;
import net.mcreator.purumod.block.BirchTinyLog02Block;
import net.mcreator.purumod.block.BirchTinyLog01Block;
import net.mcreator.purumod.block.AxeInStumbBlock;
import net.mcreator.purumod.block.AcaciaWoodenStoolBlock;
import net.mcreator.purumod.block.AcaciaTinyLog12Block;
import net.mcreator.purumod.block.AcaciaTinyLog11Block;
import net.mcreator.purumod.block.AcaciaTinyLog10Block;
import net.mcreator.purumod.block.AcaciaTinyLog09Block;
import net.mcreator.purumod.block.AcaciaTinyLog08Block;
import net.mcreator.purumod.block.AcaciaTinyLog07Block;
import net.mcreator.purumod.block.AcaciaTinyLog06Block;
import net.mcreator.purumod.block.AcaciaTinyLog05Block;
import net.mcreator.purumod.block.AcaciaTinyLog04Block;
import net.mcreator.purumod.block.AcaciaTinyLog03Block;
import net.mcreator.purumod.block.AcaciaTinyLog02Block;
import net.mcreator.purumod.block.AcaciaTinyLog01Block;
import net.mcreator.purumod.PurumodMod;

public class PurumodModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PurumodMod.MODID);
	public static final RegistryObject<Block> OAK_WOODEN_STOOL = REGISTRY.register("oak_wooden_stool", () -> new OakWoodenStoolBlock());
	public static final RegistryObject<Block> BIRCH_WOODEN_STOOL = REGISTRY.register("birch_wooden_stool", () -> new BirchWoodenStoolBlock());
	public static final RegistryObject<Block> DARK_OAK_WOODEN_STOOL = REGISTRY.register("dark_oak_wooden_stool", () -> new DarkOakWoodenStoolBlock());
	public static final RegistryObject<Block> SPRUCE_WOODEN_STOOL = REGISTRY.register("spruce_wooden_stool", () -> new SpruceWoodenStoolBlock());
	public static final RegistryObject<Block> ACACIA_WOODEN_STOOL = REGISTRY.register("acacia_wooden_stool", () -> new AcaciaWoodenStoolBlock());
	public static final RegistryObject<Block> JUNGLE_WOODEN_STOOL = REGISTRY.register("jungle_wooden_stool", () -> new JungleWoodenStoolBlock());
	public static final RegistryObject<Block> OAK_WOODEN_CHAIR = REGISTRY.register("oak_wooden_chair", () -> new OakWoodenChairBlock());
	public static final RegistryObject<Block> OAK_TINY_LOG_01 = REGISTRY.register("oak_tiny_log_01", () -> new OakTinyLog01Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_02 = REGISTRY.register("oak_tiny_log_02", () -> new OakTinyLog02Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_12 = REGISTRY.register("oak_tiny_log_12", () -> new OakTinyLog12Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_01 = REGISTRY.register("spruce_tiny_log_01", () -> new SpruceTinyLog01Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_11 = REGISTRY.register("oak_tiny_log_11", () -> new OakTinyLog11Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_10 = REGISTRY.register("oak_tiny_log_10", () -> new OakTinyLog10Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_09 = REGISTRY.register("oak_tiny_log_09", () -> new OakTinyLog09Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_08 = REGISTRY.register("oak_tiny_log_08", () -> new OakTinyLog08Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_07 = REGISTRY.register("oak_tiny_log_07", () -> new OakTinyLog07Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_06 = REGISTRY.register("oak_tiny_log_06", () -> new OakTinyLog06Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_05 = REGISTRY.register("oak_tiny_log_05", () -> new OakTinyLog05Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_04 = REGISTRY.register("oak_tiny_log_04", () -> new OakTinyLog04Block());
	public static final RegistryObject<Block> OAK_TINY_LOG_03 = REGISTRY.register("oak_tiny_log_03", () -> new OakTinyLog03Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_02 = REGISTRY.register("spruce_tiny_log_02", () -> new SpruceTinyLog02Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_03 = REGISTRY.register("spruce_tiny_log_03", () -> new SpruceTinyLog03Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_04 = REGISTRY.register("spruce_tiny_log_04", () -> new SpruceTinyLog04Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_05 = REGISTRY.register("spruce_tiny_log_05", () -> new SpruceTinyLog05Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_06 = REGISTRY.register("spruce_tiny_log_06", () -> new SpruceTinyLog06Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_07 = REGISTRY.register("spruce_tiny_log_07", () -> new SpruceTinyLog07Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_08 = REGISTRY.register("spruce_tiny_log_08", () -> new SpruceTinyLog08Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_09 = REGISTRY.register("spruce_tiny_log_09", () -> new SpruceTinyLog09Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_10 = REGISTRY.register("spruce_tiny_log_10", () -> new SpruceTinyLog10Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_11 = REGISTRY.register("spruce_tiny_log_11", () -> new SpruceTinyLog11Block());
	public static final RegistryObject<Block> SPRUCE_TINY_LOG_12 = REGISTRY.register("spruce_tiny_log_12", () -> new SpruceTinyLog12Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_01 = REGISTRY.register("jungle_tiny_log_01", () -> new JungleTinyLog01Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_01 = REGISTRY.register("birch_tiny_log_01", () -> new BirchTinyLog01Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_01 = REGISTRY.register("dark_oak_tiny_log_01", () -> new DarkOakTinyLog01Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_01 = REGISTRY.register("acacia_tiny_log_01", () -> new AcaciaTinyLog01Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_02 = REGISTRY.register("acacia_tiny_log_02", () -> new AcaciaTinyLog02Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_02 = REGISTRY.register("birch_tiny_log_02", () -> new BirchTinyLog02Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_02 = REGISTRY.register("dark_oak_tiny_log_02", () -> new DarkOakTinyLog02Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_02 = REGISTRY.register("jungle_tiny_log_02", () -> new JungleTinyLog02Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_03 = REGISTRY.register("acacia_tiny_log_03", () -> new AcaciaTinyLog03Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_03 = REGISTRY.register("birch_tiny_log_03", () -> new BirchTinyLog03Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_03 = REGISTRY.register("dark_oak_tiny_log_03", () -> new DarkOakTinyLog03Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_03 = REGISTRY.register("jungle_tiny_log_03", () -> new JungleTinyLog03Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_04 = REGISTRY.register("acacia_tiny_log_04", () -> new AcaciaTinyLog04Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_04 = REGISTRY.register("birch_tiny_log_04", () -> new BirchTinyLog04Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_04 = REGISTRY.register("dark_oak_tiny_log_04", () -> new DarkOakTinyLog04Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_04 = REGISTRY.register("jungle_tiny_log_04", () -> new JungleTinyLog04Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_05 = REGISTRY.register("acacia_tiny_log_05", () -> new AcaciaTinyLog05Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_05 = REGISTRY.register("birch_tiny_log_05", () -> new BirchTinyLog05Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_05 = REGISTRY.register("dark_oak_tiny_log_05", () -> new DarkOakTinyLog05Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_05 = REGISTRY.register("jungle_tiny_log_05", () -> new JungleTinyLog05Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_06 = REGISTRY.register("acacia_tiny_log_06", () -> new AcaciaTinyLog06Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_06 = REGISTRY.register("birch_tiny_log_06", () -> new BirchTinyLog06Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_06 = REGISTRY.register("dark_oak_tiny_log_06", () -> new DarkOakTinyLog06Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_06 = REGISTRY.register("jungle_tiny_log_06", () -> new JungleTinyLog06Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_07 = REGISTRY.register("acacia_tiny_log_07", () -> new AcaciaTinyLog07Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_07 = REGISTRY.register("birch_tiny_log_07", () -> new BirchTinyLog07Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_07 = REGISTRY.register("dark_oak_tiny_log_07", () -> new DarkOakTinyLog07Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_07 = REGISTRY.register("jungle_tiny_log_07", () -> new JungleTinyLog07Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_08 = REGISTRY.register("acacia_tiny_log_08", () -> new AcaciaTinyLog08Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_08 = REGISTRY.register("birch_tiny_log_08", () -> new BirchTinyLog08Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_08 = REGISTRY.register("dark_oak_tiny_log_08", () -> new DarkOakTinyLog08Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_08 = REGISTRY.register("jungle_tiny_log_08", () -> new JungleTinyLog08Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_09 = REGISTRY.register("acacia_tiny_log_09", () -> new AcaciaTinyLog09Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_09 = REGISTRY.register("birch_tiny_log_09", () -> new BirchTinyLog09Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_09 = REGISTRY.register("dark_oak_tiny_log_09", () -> new DarkOakTinyLog09Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_09 = REGISTRY.register("jungle_tiny_log_09", () -> new JungleTinyLog09Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_10 = REGISTRY.register("acacia_tiny_log_10", () -> new AcaciaTinyLog10Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_10 = REGISTRY.register("birch_tiny_log_10", () -> new BirchTinyLog10Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_10 = REGISTRY.register("dark_oak_tiny_log_10", () -> new DarkOakTinyLog10Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_10 = REGISTRY.register("jungle_tiny_log_10", () -> new JungleTinyLog10Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_11 = REGISTRY.register("acacia_tiny_log_11", () -> new AcaciaTinyLog11Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_11 = REGISTRY.register("birch_tiny_log_11", () -> new BirchTinyLog11Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_11 = REGISTRY.register("dark_oak_tiny_log_11", () -> new DarkOakTinyLog11Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_11 = REGISTRY.register("jungle_tiny_log_11", () -> new JungleTinyLog11Block());
	public static final RegistryObject<Block> ACACIA_TINY_LOG_12 = REGISTRY.register("acacia_tiny_log_12", () -> new AcaciaTinyLog12Block());
	public static final RegistryObject<Block> BIRCH_TINY_LOG_12 = REGISTRY.register("birch_tiny_log_12", () -> new BirchTinyLog12Block());
	public static final RegistryObject<Block> DARK_OAK_TINY_LOG_12 = REGISTRY.register("dark_oak_tiny_log_12", () -> new DarkOakTinyLog12Block());
	public static final RegistryObject<Block> JUNGLE_TINY_LOG_12 = REGISTRY.register("jungle_tiny_log_12", () -> new JungleTinyLog12Block());
	public static final RegistryObject<Block> AXE_IN_STUMB = REGISTRY.register("axe_in_stumb", () -> new AxeInStumbBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			OakWoodenStoolBlock.registerRenderLayer();
			BirchWoodenStoolBlock.registerRenderLayer();
			DarkOakWoodenStoolBlock.registerRenderLayer();
			SpruceWoodenStoolBlock.registerRenderLayer();
			AcaciaWoodenStoolBlock.registerRenderLayer();
			JungleWoodenStoolBlock.registerRenderLayer();
			OakWoodenChairBlock.registerRenderLayer();
			OakTinyLog01Block.registerRenderLayer();
			OakTinyLog02Block.registerRenderLayer();
			OakTinyLog12Block.registerRenderLayer();
			SpruceTinyLog01Block.registerRenderLayer();
			OakTinyLog11Block.registerRenderLayer();
			OakTinyLog10Block.registerRenderLayer();
			OakTinyLog09Block.registerRenderLayer();
			OakTinyLog08Block.registerRenderLayer();
			OakTinyLog07Block.registerRenderLayer();
			OakTinyLog06Block.registerRenderLayer();
			OakTinyLog05Block.registerRenderLayer();
			OakTinyLog04Block.registerRenderLayer();
			OakTinyLog03Block.registerRenderLayer();
			SpruceTinyLog02Block.registerRenderLayer();
			SpruceTinyLog03Block.registerRenderLayer();
			SpruceTinyLog04Block.registerRenderLayer();
			SpruceTinyLog05Block.registerRenderLayer();
			SpruceTinyLog06Block.registerRenderLayer();
			SpruceTinyLog07Block.registerRenderLayer();
			SpruceTinyLog08Block.registerRenderLayer();
			SpruceTinyLog09Block.registerRenderLayer();
			SpruceTinyLog10Block.registerRenderLayer();
			SpruceTinyLog11Block.registerRenderLayer();
			SpruceTinyLog12Block.registerRenderLayer();
			JungleTinyLog01Block.registerRenderLayer();
			BirchTinyLog01Block.registerRenderLayer();
			DarkOakTinyLog01Block.registerRenderLayer();
			AcaciaTinyLog01Block.registerRenderLayer();
			AcaciaTinyLog02Block.registerRenderLayer();
			BirchTinyLog02Block.registerRenderLayer();
			DarkOakTinyLog02Block.registerRenderLayer();
			JungleTinyLog02Block.registerRenderLayer();
			AcaciaTinyLog03Block.registerRenderLayer();
			BirchTinyLog03Block.registerRenderLayer();
			DarkOakTinyLog03Block.registerRenderLayer();
			JungleTinyLog03Block.registerRenderLayer();
			AcaciaTinyLog04Block.registerRenderLayer();
			BirchTinyLog04Block.registerRenderLayer();
			DarkOakTinyLog04Block.registerRenderLayer();
			JungleTinyLog04Block.registerRenderLayer();
			AcaciaTinyLog05Block.registerRenderLayer();
			BirchTinyLog05Block.registerRenderLayer();
			DarkOakTinyLog05Block.registerRenderLayer();
			JungleTinyLog05Block.registerRenderLayer();
			AcaciaTinyLog06Block.registerRenderLayer();
			BirchTinyLog06Block.registerRenderLayer();
			DarkOakTinyLog06Block.registerRenderLayer();
			JungleTinyLog06Block.registerRenderLayer();
			AcaciaTinyLog07Block.registerRenderLayer();
			BirchTinyLog07Block.registerRenderLayer();
			DarkOakTinyLog07Block.registerRenderLayer();
			JungleTinyLog07Block.registerRenderLayer();
			AcaciaTinyLog08Block.registerRenderLayer();
			BirchTinyLog08Block.registerRenderLayer();
			DarkOakTinyLog08Block.registerRenderLayer();
			JungleTinyLog08Block.registerRenderLayer();
			AcaciaTinyLog09Block.registerRenderLayer();
			BirchTinyLog09Block.registerRenderLayer();
			DarkOakTinyLog09Block.registerRenderLayer();
			JungleTinyLog09Block.registerRenderLayer();
			AcaciaTinyLog10Block.registerRenderLayer();
			BirchTinyLog10Block.registerRenderLayer();
			DarkOakTinyLog10Block.registerRenderLayer();
			JungleTinyLog10Block.registerRenderLayer();
			AcaciaTinyLog11Block.registerRenderLayer();
			BirchTinyLog11Block.registerRenderLayer();
			DarkOakTinyLog11Block.registerRenderLayer();
			JungleTinyLog11Block.registerRenderLayer();
			AcaciaTinyLog12Block.registerRenderLayer();
			BirchTinyLog12Block.registerRenderLayer();
			DarkOakTinyLog12Block.registerRenderLayer();
			JungleTinyLog12Block.registerRenderLayer();
			AxeInStumbBlock.registerRenderLayer();
		}
	}
}
